spring.application.name=app

# username
spring.datasource.hikari.username=${DB_USERNAME}
# password
spring.datasource.hikari.password=${DB_PASSWORD}
# url
spring.datasource.url=${DB_URL}
# driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# JWT Configurations
jwt.secret=${JWT_SECRET:defaultLocalDevelopmentDummySecretKeyDoNotUseInProduction12345678}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

# FastAPI Configuration
ai.fastapi.base-url=${AI_FASTAPI_BASE_URL:http://localhost:8000}